#!/bin/bash

set -o xtrace

#./bin/program ../mpeg/ERP001960/NA12878_S1.sam 1960_12878_compressed ../mpeg/ERP001960/hg19.fa


./bin/program /john9/scr1/reglong/ERP002490/NA12877_S1.sam  /john9/scr1/reglong/ERP002490/12877_compressed /john9/scr1/reglong/ERP002490/hg19.fa
